AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Protein Tracker API

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  ProteinTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/protein_tracker/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /protein
            Method: ANY

Outputs:
  ApiURL:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"